services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
  local_rag_llm:
    build:
      dockerfile: Dockerfile
    image: local_rag_llm
    environment:
      HF_TOKEN: <your HF token>
    depends_on:
      - postgres
    volumes:
      - <your local volume>:/app
      - <your local volume with models>:/app/models
    tty: true # keep the container running